import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { z } from "zod";
import {
  BranchSchema,
  CourseTagSchema,
  SkillEdgeSchema,
  TagSkillMapEntrySchema,
} from "@/schemas";
import branchesJson from "@/data/branches.json";
import skillEdgesJson from "@/data/skill_edges.json";
import skillsJson from "@/data/skills.json";

// The merged evidence layer: skill_edges.json and branches.json are generated by
// pipeline/merge_edges.py and must parse through the shared Zod schemas; the
// invariants below are the ones the engine (path-driving edges only) and the UI
// (transition shares with caveats) rely on.

const repo = join(__dirname, "..");
const skills = skillsJson as { id: string; prereqs: string[] }[];
const ids = new Set(skills.map((s) => s.id));
const authored = new Set(skills.flatMap((s) => s.prereqs.map((p) => `${p}>${s.id}`)));

describe("skill_edges.json", () => {
  const edges = z.array(SkillEdgeSchema).parse((skillEdgesJson as { edges: unknown[] }).edges);

  it("parses and references only existing skills", () => {
    expect(edges.length).toBeGreaterThan(0);
    const dangling = edges.filter((e) => !ids.has(e.from) || !ids.has(e.to));
    expect(dangling).toEqual([]);
  });

  it("carries exactly the authored prereq edges as origin authored, all path-driving", () => {
    const auth = edges.filter((e) => e.origin === "authored");
    expect(new Set(auth.map((e) => `${e.from}>${e.to}`))).toEqual(authored);
    expect(auth.every((e) => e.drivesPath)).toBe(true);
  });

  it("mined edges never duplicate an authored pair and drive paths only when promoted", () => {
    const mined = edges.filter((e) => e.origin === "mined");
    expect(mined.filter((e) => authored.has(`${e.from}>${e.to}`) || authored.has(`${e.to}>${e.from}`))).toEqual([]);
    expect(mined.filter((e) => e.drivesPath !== (e.status === "promoted"))).toEqual([]);
    expect(mined.filter((e) => Object.keys(e.sources).length === 0)).toEqual([]);
  });

  it("every source block carries support, reverse, confidence, n and a caveat with no satisfaction wording", () => {
    for (const e of edges) {
      for (const st of Object.values(e.sources)) {
        expect(st.n).toBe(st.support + st.reverse);
        expect(Math.abs(st.confidence - st.support / st.n)).toBeLessThan(1e-5);
        expect(st.caveat.toLowerCase()).not.toMatch(/satisfied|struggled|liked|\bhard\b/);
      }
    }
  });

  it("path-driving edges form a DAG", () => {
    const adj = new Map<string, string[]>();
    for (const e of edges.filter((e) => e.drivesPath)) {
      adj.set(e.from, [...(adj.get(e.from) ?? []), e.to]);
    }
    const state = new Map<string, number>();
    const visit = (n: string): boolean => {
      if (state.get(n) === 1) return false;
      if (state.get(n) === 2) return true;
      state.set(n, 1);
      for (const m of adj.get(n) ?? []) if (!visit(m)) return false;
      state.set(n, 2);
      return true;
    };
    expect([...adj.keys()].every(visit)).toBe(true);
  });
});

describe("branches.json", () => {
  const branches = z.array(BranchSchema).parse((branchesJson as { branches: unknown[] }).branches);

  it("parses, one entry per (from, source), endpoints exist", () => {
    expect(branches.length).toBeGreaterThan(0);
    expect(new Set(branches.map((b) => `${b.from}|${b.source}`)).size).toBe(branches.length);
    expect(branches.filter((b) => !ids.has(b.from) || b.next.some((x) => !ids.has(x.to)))).toEqual([]);
  });

  it("shares are transition shares under the floors: listed at n >= 5, minSupportMet = nTotal >= 50, sums <= 1 (= 1 when every successor is listed)", () => {
    for (const b of branches) {
      expect(b.minSupportMet).toBe(b.nTotal >= 50);
      const raw = b.next.reduce((s, x) => s + x.shareRaw, 0);
      const shrunk = b.next.reduce((s, x) => s + x.shareShrunk, 0);
      expect(raw).toBeLessThanOrEqual(1 + 1e-6);
      expect(shrunk).toBeLessThanOrEqual(1 + 1e-6);
      if (b.next.length === b.nNextObserved) {
        expect(Math.abs(raw - 1)).toBeLessThan(1e-6);
        expect(Math.abs(shrunk - 1)).toBeLessThan(1e-6);
      }
      for (const x of b.next) expect(Math.abs(x.shareRaw - x.n / b.nTotal)).toBeLessThan(1e-6);
      expect(b.caveat.toLowerCase()).not.toMatch(/satisfied|struggled|liked|\bhard\b/);
    }
  });
});

describe("pipeline evidence sources", () => {
  it("course_skill_tags.json rows parse through CourseTagSchema", () => {
    const doc = JSON.parse(readFileSync(join(repo, "pipeline", "evidence", "course_skill_tags.json"), "utf8"));
    const tags = z.array(CourseTagSchema).parse(doc.tags);
    expect(tags.length).toBeGreaterThan(0);
    expect(tags.flatMap((t) => t.skillsTaught).filter((s) => !ids.has(s.skillId))).toEqual([]);
  });

  it("tag_skill_map.json rows parse through TagSkillMapEntrySchema", () => {
    const doc = JSON.parse(readFileSync(join(repo, "pipeline", "sources", "tag_skill_map.json"), "utf8"));
    const rows = z.array(TagSkillMapEntrySchema).parse(doc.rows);
    expect(rows.length).toBeGreaterThan(0);
    expect(rows.filter((r) => !ids.has(r.skillId))).toEqual([]);
  });
});
