import { eq } from "drizzle-orm";
import { db, chatMessages, feedbackEvents, learners, paths, profiles, tokenUsage, users } from "../src/db";
import { generatePath } from "../src/engine";
import { applyProfileOps } from "../src/engine/profile";
import { applyFeedback } from "../src/engine/replan";
import { demoAt } from "../src/lib/demoStory";
import { loadEngineData } from "../src/lib/engineData";
import { buildProfileCard } from "../src/lib/profileCard";
import type { Path, PathDiff, Profile } from "../src/schemas";
import { PERSONAS, type Persona } from "./personas";

/**
 * Seeds the demo learners onto an existing signed-in Google account:
 *
 *   npm run seed <owner-email>            # all three personas
 *   npm run seed <owner-email> priya      # one persona
 *
 * Every path version is generated by the engine and every replan comes from a feedback event
 * run through the product's own rules; nothing is hand-written into the database. Re-running
 * replaces that account's copy of each persona.
 */
const OWNER_EMAIL = process.argv[2];
const WHICH = process.argv[3] ?? "all";
if (!OWNER_EMAIL) {
  console.error("usage: seed-demo.ts <owner-email> [alex|priya|sam|all]");
  process.exit(1);
}
const selected = WHICH === "all" ? Object.values(PERSONAS) : [PERSONAS[WHICH]];
if (selected.some((p) => !p)) {
  console.error(`Unknown persona "${WHICH}"; choose one of ${Object.keys(PERSONAS).join(", ")} or all`);
  process.exit(1);
}

const at = demoAt;

async function seedPersona(conn: ReturnType<typeof db>, ownerId: string, persona: Persona) {
  const data = loadEngineData();
  const catalogIds = new Set(data.catalog.map((c) => c.id));

  // Replace any previous copy so the script is safe to re-run.
  const existing = await conn.select().from(learners).where(eq(learners.displayName, persona.displayName));
  for (const row of existing.filter((l) => l.userId === ownerId)) {
    await conn.delete(tokenUsage).where(eq(tokenUsage.learnerId, row.id));
    await conn.delete(chatMessages).where(eq(chatMessages.learnerId, row.id));
    await conn.delete(feedbackEvents).where(eq(feedbackEvents.learnerId, row.id));
    await conn.delete(paths).where(eq(paths.learnerId, row.id));
    await conn.delete(profiles).where(eq(profiles.learnerId, row.id));
    await conn.delete(learners).where(eq(learners.id, row.id));
  }

  const born = persona.createdDaysAgo;
  const empty: Profile = { goals: [], skills: {}, preferences: { hoursPerWeek: 6, formats: [], budget: "any", pace: "standard" } };
  const [learner] = await conn
    .insert(learners)
    .values({ userId: ownerId, displayName: persona.displayName, avatarSeed: persona.avatarSeed, createdAt: at(born, 19) })
    .returning();

  // A learner who has not spoken yet: the empty profile and nothing else.
  if (persona.openingOps.length === 0) {
    await conn.insert(profiles).values({ learnerId: learner.id, data: empty, updatedAt: at(born, 19) });
    console.log(`Seeded "${persona.displayName}" — ${persona.shows}`);
    console.log(`  learner  ${learner.id}`);
    console.log(`  open     /learn/${learner.id}`);
    return;
  }

  // Goal + the levels Nova inferred from the first message, then the levels the learner corrected on the card.
  let profile: Profile = applyProfileOps(empty, persona.openingOps);
  const card = buildProfileCard("seed-card", profile, data);
  if ("error" in card) throw new Error(card.error);
  profile = applyProfileOps(profile, persona.cardAnswer);
  await conn.insert(profiles).values({ learnerId: learner.id, data: profile, updatedAt: at(born, 19, 6) });

  const first = generatePath(profile, data, { now: at(born, 19, 7).toISOString(), trigger: "initial" });
  let path: Path = first.path;
  let version = 1;
  let latestPathId = (await conn.insert(paths).values({ learnerId: learner.id, version, data: path, diff: null, createdAt: at(born, 19, 7) }).returning())[0].id;

  const counts = { chat: 0, feedback: 0, replans: 0, skippedEvents: [] as string[] };
  for (const step of persona.story) {
    const when = at(step.day, 20, step.minute ?? 0);
    if (step.kind === "chat") {
      const content: { text: string; toolCalls?: string[]; card?: typeof card } = { text: step.text };
      if (step.toolCalls) content.toolCalls = step.toolCalls;
      if (step.card) content.card = card;
      await conn.insert(chatMessages).values({ learnerId: learner.id, role: step.role, content, createdAt: when });
      counts.chat += 1;
      // A profile change the conversation records is a real op, applied where the story says it happened.
      const ops = persona.opsOnDay?.[step.day];
      if (ops && step.toolCalls?.includes("apply_profile_ops") && step.role === "assistant" && step.day !== born) {
        profile = applyProfileOps(profile, ops);
        await conn.update(profiles).set({ data: profile, updatedAt: when }).where(eq(profiles.learnerId, learner.id));
      }
      continue;
    }
    const { event } = step;
    // Only events the live route would accept: items must be on the current path, skills must exist.
    if ("catalogId" in event) {
      const onPath = path.phases.some((p) => p.items.some((i) => i.catalogId === event.catalogId));
      if (!catalogIds.has(event.catalogId) || !onPath) {
        counts.skippedEvents.push(`${event.type}:${event.catalogId}`);
        continue;
      }
    } else if (!data.skills.some((s) => s.id === event.skillId)) {
      counts.skippedEvents.push(`${event.type}:${event.skillId}`);
      continue;
    }
    const [stored] = await conn.insert(feedbackEvents).values({ learnerId: learner.id, type: event.type, payload: event, createdAt: when }).returning();
    const result = applyFeedback(event, { profile, path, data, now: when.toISOString(), eventId: stored.id });
    profile = result.profile;
    path = result.path;
    await conn.update(profiles).set({ data: profile, updatedAt: when }).where(eq(profiles.learnerId, learner.id));
    if (result.replanned) {
      version += 1;
      latestPathId = (await conn.insert(paths).values({ learnerId: learner.id, version, data: path, diff: result.diff as PathDiff, createdAt: when }).returning())[0].id;
      counts.replans += 1;
    } else {
      await conn.update(paths).set({ data: path }).where(eq(paths.id, latestPathId));
    }
    counts.feedback += 1;
  }

  const items = path.phases.flatMap((p) => p.items);
  console.log(`Seeded "${persona.displayName}" — ${persona.shows}`);
  console.log(`  learner  ${learner.id}`);
  console.log(`  chat     ${counts.chat} messages`);
  console.log(`  feedback ${counts.feedback} events, ${counts.replans} replans → path v${version}`);
  console.log(`  path     ${path.phases.length} phases, ${items.length} items, ${items.filter((i) => i.status === "done").length} done`);
  if (counts.skippedEvents.length) console.log(`  skipped  ${counts.skippedEvents.join(", ")} (not on the path at that point — adjust the story)`);
  console.log(`  open     /learn/${learner.id}`);
}

async function main() {
  const conn = db();
  const [owner] = await conn.select().from(users).where(eq(users.email, OWNER_EMAIL));
  if (!owner) throw new Error(`No user with email ${OWNER_EMAIL} — sign in once first`);
  for (const persona of selected) await seedPersona(conn, owner.id, persona);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
